baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
disqusShortname = ""
googleAnalytics = ""
[module]
    [[module.imports]]
    path = 'github.com/mockeryofthearts/mockery-of-the-arts-theme'
